site_name: Scilla
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - tags:
     tags_file: tag.md

nav:
 - Buongiorno: 
   - index.md
   - Cibo/mela.md
 - Buonasera: prova.md
 - Tag: tag.md